logging:
  file: logs/anime-fetcher.log
  level:
    org.springframework: INFO
    com.irt.workout.anime: INFO
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"

localPath: D:\\films\\anime
animeInfoFilePath: D:\\films\\anime\\anime-fetcher\\anime-info.json